### ISSUE TITLE
Settings Page Layout is broken.

### ISSUE THREAD

**Issue by wjeffreybrown** [FourthEstateOrg/Newswire-Publisher#5]
The layout of the settings page is broken. 

It should look like this.
<img width="1210" alt="Screen Shot 2022-08-27 at 9 03 10 AM" src="https://user-images.githubusercontent.com/97678551/187031589-0104d575-ff9b-4c6c-b95b-993a346d5cd4.png">
o

**Comment by zildjianjax** [comment]
This is fixed
