### ISSUE TITLE
Link to settings page is broken

### ISSUE THREAD

**Issue by wjeffreybrown** [FourthEstateOrg/Newswire-Publisher#6]
The link to the settings page on the plugin page is broken.

The error is:  Sorry, you are not allowed to access this page.

<img width="1155" alt="Screen Shot 2022-08-27 at 9 10 06 AM" src="https://user-images.githubusercontent.com/97678551/187031719-278dac07-af3e-4b2a-84dd-fd418430f7ab.png">

**Comment by zildjianjax** [comment]
This is fixed
